services:
  - type: web
    name: santasa-crm-api
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: "postgresql://postgres.vdwpxcdpzhreonutitrc:cmW7zEtAJH5ziFyo@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require"
      - key: SUPABASE_URL
        value: "https://vdwpxcdpzhreonutitrc.supabase.co"
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkd3B4Y2RwemhyZW9udXRpdHJjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjY3OTQ0OSwiZXhwIjoyMTAyMjU1NDQ5fQ.e_H5V4N7x94W5iV8d-aU9QW6zE2oP4Y3bK8X1jM0rNs"
      - key: SECRET_KEY
        value: "santasa-ivf-lead-management-crm-super-secure-production-jwt-key-2026"
      - key: CORS_ORIGINS
        value: "*"
